### ISSUE TITLE
Collection Sorting

### ISSUE THREAD

**Issue by JR202** [GSA/project-open-data-dashboard#103]
Data.gov received this data suggestion from the public (Report ID-6282 via Help Desk): 

Collection Sorting- When a collection is listed individually it does not have any apparent sort order.  Please consider creating a default sort first by service type, then by service name.

**Comment by rebeccawilliams** [comment]
I think this makes the most sense as a catalog.data.gov Issue? Moved it [there](https://github.com/GSA/data.gov/issues/676)
