### ISSUE TITLE
HHS JSON, Could Not Upload File

### ISSUE THREAD

**Issue by DamonDavis** [GSA/project-open-data-dashboard#111]
I just tried to validate http://www.healthdata.gov/data.json but the validator returned "Could not upload file (it may be larger than PHP or application allows)"

**Comment by kvuppala** [comment]
@DamonDavis 
Just tried this at labs.data.gov - http://labs.data.gov/dashboard/validate?schema=federal-v1.1&output=json&datajson_url=http%3A%2F%2Fwww.healthdata.gov%2Fdata.json&qa=true 

I was able to get a successful results, see the below jsonout

{

    "errors": false,
    "qa": 

{

    "programCodes": 

[

    "009:000",
    "009:002",
    "009:076",
    "009:082",
    "009:001",
    "009:007",
    "009:005",
    "009:003",
    "009:008",
    "009:020",
    "009:078",
    "009:110",
    "009:084",
    "009:004",
    "009:047",
    "009:041",
    "009:032"

],
"bureauCodes": 
[

    "009:00",
    "009:33",
    "009:10",
    "009:38",
    "009:20",
    "009:30",
    "009:70",
    "009:25",
    "009:15",
    "009:17",
    "009:92",
    "009:75"

],
"accessLevel_public": 1647,
"accessLevel_restricted": 19,
"accessLevel_nonpublic": 0,
"accessURL_present": 1154,
"accessURL_total": 3202,
"API_total": 0,
"collections_total": 0,
"validation_counts": 

        {
            "http_5xx": 0,
            "http_4xx": 0,
            "http_3xx": 0,
            "http_2xx": 0,
            "http_0": 0,
            "pdf": 0,
            "html": 0,
            "format_mismatch": 0
        },
        "license_present": 0,
        "redaction_present": 0,
        "redaction_no_explanation": 0,
        "downloadURL_present": 1154,
        "downloadURL_total": 3202
    },
    "schema_version": "federal-v1.1",
    "valid": true,
    "valid_json": true,
    "total_records": 1666,
    "download_content_length": 2345887

}

**Comment by kvuppala** [comment]
Was able to get the "View in Browser" also work, see the below screenshot result

![labs_validate_hhs_json_file](https://cloud.githubusercontent.com/assets/1738764/10400373/45f1457a-6e86-11e5-993a-ba8de0bbe545.png)
