### ISSUE TITLE
Support large data.json files

### ISSUE THREAD

**Issue by philipashlock** [GSA/project-open-data-dashboard#12]
The current approach to parsing data.json files doesn't scale with large files (eg over 5mb), so we need to switch to more of a file streaming or chunking strategy

**Comment by davidread** [comment]
No doubt you're aware of things like ijson to deal with a chunk of JSON at a time. https://pypi.python.org/pypi/ijson/2.2

Another thought might be to accept datasets in JSON lines: http://jsonlines.org/

**Comment by philipashlock** [comment]
This is done
