### ISSUE TITLE
missing fields from exports 

### ISSUE THREAD

**Issue by gbinal** [GSA/project-open-data-dashboard#2]
It looks like keywords, contact name, contact people, temporal, data dictionary, frequency, spatial, theme aren't making it into the csv or json exports.   

For instance, compare http://catalog.data.gov/dataset/va-personal-health-record-non-identifiable-data 
and 
http://datafarm.civicagency.org/datagov/convert?orgs=vha-va-gov
or 
http://datafarm.civicagency.org/datagov/csv?orgs=vha-va-gov

**Comment by rebeccawilliams** [comment]
Seems like this has been addressed for v 1.0 and v 1.1. Please re-open if I am mistaken (looks there recent commits have referenced this Issue).
