### ISSUE TITLE
Realign milestone dates with regular FDS quarterly milestones

### ISSUE THREAD

**Issue by philipashlock** [GSA/project-open-data-dashboard#261]
We should change the dates so that Milestone 27 ends on March 31st and align the quarterly milestones with OMB's regular quarterly dates from there moving forward. This should simply involve an update to the [milestones_model()](https://github.com/GSA/project-open-data-dashboard/blob/ae7a3f21a753ae055fa8b898f9e4fad442aab968/application/models/Campaign_model.php#L2129-L2153
) function so that we retain the prior milestone dates before this, but keep them in sync moving forward. 

We'll want this change live before March 31st.

**Comment by mogul** [comment]
@philipashlock we're already loaded up with work and cannot take this on before Tuesday. If you have  time yourself and want to work on it I can facilitate that. The best case scenario is that we'd take this on in our next sprint, which starts Thursday; to do that, however, we'll need you to come talk to us about why this should take priority over other work we've got lined up!

**Comment by philipashlock** [comment]
@mogul I'm confirming a few things with OMB first and might have another commit, but otherwise the PR should be good here https://github.com/GSA/project-open-data-dashboard/pull/264

**Comment by mogul** [comment]
Deployed!
