### ISSUE TITLE
U.S. Department of Veterans Affairs - Please Add

### ISSUE THREAD

**Issue by rafael5** [GSA/project-open-data-dashboard#291]
The U.S. Department of Veterans Affairs does not appear on the list of Federal Agencies.

Could you please add this?

Thank you.

Rafael Richards MD MS
Director,  Master Data and Metadata Management
U.S. Department of Veterans Affairs

**Comment by hkdctol** [comment]
Hi--it's pending on a redirect that we need VA to put in place. I just pinged on status on that.

**Comment by rafael5** [comment]
Thanks. I can help, as I am in VA.

Can you send a name?

**Comment by hkdctol** [comment]
can you email datagov@gsa.gov and I will connect you to the thread that's pending

**Comment by hkdctol** [comment]
Pinged VA on status of redirect.

**Comment by hkdctol** [comment]
The https://va.gov/data.json redirect to their harvest source is in place so it is on dashboard now. Closing issue.
