### ISSUE TITLE
Department of Transportation

### ISSUE THREAD

**Issue by GitHubNavigatorJill** [GSA/project-open-data-dashboard#311]
Am I missing something? I don't see any data for the department of Transportation. I am looking for FMCSA data for current and prior 18 months including MCS-90 data (Policy number, Effective date of Policy and Insurance Carrier Name) for Motor Carriers. Is this available? Jill Hendrickson 616-457-7100 If I am unavailable please call Ray Moss or Colin Knebl at the same number and ask for them. my email is Jhendrickson@navigatortruckinsurance.com Thanks for your assistance.

**Comment by adborden** [comment]
@GitHubNavigatorJill can you clarify? This project is only concerned with agency reporting on the federal Open Data Policy. Department of Transportation is currently not reporting.

You can still search for [Department of Transportation data on catalog.data.gov](https://catalog.data.gov/dataset?organization=dot-gov&sort=score+desc%2C+name+asc&q=FMCSA).
