### ISSUE TITLE
Federal Investigation  Authority code Analyzer Request.

### ISSUE THREAD

**Issue by nurrabazo** [GSA/project-open-data-dashboard#365]
I need a few of your best decoders to get to work on my device. Asap. I need Locations real names and the meaning of these codes and messages set on my device . I need this done now. Please !

**Comment by mogul** [comment]
This GitHub repository is specifically for discussion around the development of data.gov, which is unrelated to your inquiry. If you have a specific request for a service of the US Federal Government, the best place to start is https://usa.gov.
