### ISSUE TITLE
Provide some background

### ISSUE THREAD

**Issue by nsinai** [GSA/project-open-data-dashboard#39]
I assume this is the homepage for the tracker?

http://labs.data.gov/dashboard/offices

If so, it's really unclear to the first time user what this is for.

Should we add text like:

"This is a public dashboard showing how Federal agencies are performing on the Open Data Policy -- formally known as OMB-13-13"

**Comment by rebeccawilliams** [comment]
Looks like some text was added last year. Also moving this dashboard to Project Open Data (and harmonizing the content between the 2) would help to clear this up, see #99.
