### ISSUE TITLE
Primary "@type" key deserializing error

### ISSUE THREAD

**Issue by jeffgroversr** [GSA/project-open-data-dashboard#400]
When deserializing the json, the primary "@type" key is not being read by python. Please see extract code below:

class User:
    def __init__(self, @type):
        self.type = @type 

We are getting this error:
    def __init__(self, @type):
                              ^
SyntaxError: invalid syntax

Below is a snipid of the json. When this key is removed, then it deserializing correctly. Note, the minor "@type" keys are not throwing an error. Just the primary key

Any suggestions would be helpful.

[
{ "@type": "dcat:Dataset", "modified": "2007-07-26",
  "title": "Agency Parking", 
  "description": "Agency parking application that provides", 
  "accessLevel": "non-public", 
  "identifier": "DOE-019-NP-10004",
  "contactPoint": {"@type": "vcard:Contact","fn": "Bao Le","hasEmail": "mailto:bao.le@ed.gov"},
  "license": "https://creativecommons.org/publicdomain/zero/1.0/",
  "temporal": "2002/2003",
  "accrualPeriodicity": "R/P2Y",
  "dataQuality": true,
  "issued": "2005-12-13",
  "landingPage": "https://nces.ed.gov/surveys/libraries/academic.asp",
  "systemOfRecords": "https://www2.ed.gov/notices/pai/pai-18-13-01.pdf",
  "spatial": "United States",
  "keyword": ["Research libraries","Research librarians","University libraries","College libraries","University librarians","College librarians"],
  "distribution": [{
                   "@type": "dcat:Distribution",
                   "description": "2004 Academic Libraries Study data as a zipped TSV file",
                   "downloadURL": "https://nces.ed.gov/pubs2007/data/ALS2004_ASCII.zip",
                   "format": "Zipped TSV",
                   "mediaType": "application/zip",
                   "title": "ALS2004_ASCII.zip"
                  },
			       {
                   "@type": "dcat:Distribution",
                   "description": "2004 Academic Libraries Study data as a zipped Microsoft Office Access database file",
                   "downloadURL": "https://nces.ed.gov/pubs2007/data/ALS2004_Access.zip",
                   "format": "Zipped MDB",
                   "mediaType": "application/zip",
                   "title": "ALS2004_Access.zip"
                  }],
  "bureauCode": ["018:50"],
  "programCode": ["018:000"],
  "language": ["en-US"],
  "references": ["https://nces.ed.gov/pubs2006/2006308.pdf"],
  "publisher": {"@type": "org:Organization"}
},
  
{ "@type": "dcat:Dataset", "modified": "2007-07-26",
  "title": "Congressional and Intergovernmental Affairs webpage", 
  "description": "The Office of Congressional and Intergovernmental", 
  "accessLevel": "public", 
  "identifier": "DOE-019-4578239451",
  "contactPoint": {"@type": "vcard:Contact","fn": "Bao Le","hasEmail": "mailto:bao.le@ed.gov"},
  "license": "https://creativecommons.org/publicdomain/zero/1.0/",
  "temporal": "2002/2003",
  "accrualPeriodicity": "R/P2Y",
  "dataQuality": true,
  "issued": "2005-12-13",
  "landingPage": "https://nces.ed.gov/surveys/libraries/academic.asp",
  "systemOfRecords": "https://www2.ed.gov/notices/pai/pai-18-13-01.pdf",
  "spatial": "United States",
  "keyword": ["Research libraries","Research librarians","University libraries","College libraries","University librarians","College librarians"],
  "distribution": [{
                   "@type": "dcat:Distribution",
                   "description": "2006 Academic Libraries Study data as a zipped TSV file",
                   "downloadURL": "https://nces.ed.gov/pubs2008/data/ALS2006_ASCII.zip",
                   "format": "Zipped TSV",
                   "mediaType": "application/zip",
                   "title": "ALS2006_ASCII.zip"
                   },
			    {
                   "@type": "dcat:Distribution",
                   "description": "2006 Academic Libraries Study data as a zipped Microsoft Office Access database file",
                   "downloadURL": "https://nces.ed.gov/pubs2008/data/ALS2006_Access.zip",
                   "format": "Zipped MDB",
                   "mediaType": "application/zip",
                   "title": "ALS2006_Access.zip"
                }],
  "bureauCode": ["018:50"],
  "programCode": ["018:000"],
  "language": ["en-US"],
  "references": ["https://nces.ed.gov/pubs2006/2006308.pdf"],
  "publisher": {"@type": "org:Organization"}
}
]

**Comment by jbrown-xentity** [comment]
Thanks for the report! Unfortunately, GSA plans to deprecate this specific tool and provide a different service in the future for validating DCAT-US files. Please watch https://github.com/gsa/ckanext-datajson for new features hopefully coming soon!
