### ISSUE TITLE
CSV Error Logs

### ISSUE THREAD

**Issue by josephhyatt** [GSA/project-open-data-dashboard#406]
Hi, I have a URL validator I created that I wanted to compare to this validator, and I see in the documentation this validator should have CSV error logs, but I can't where these logs are located.

**Comment by jbrown-xentity** [comment]
We are actually in the process of deprecating this system. We are replacing it's features with a variety of things:
- Metrics Dashboard (https://github.com/GSA/data.gov/issues/4016)
- New validator (https://github.com/GSA/data.gov/issues/3503), see https://catalog.data.gov/dcat-us/validator for working version and [here](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/helpers.py#L156) for the starting point of the validation code
