### ISSUE TITLE
SBA data.json file URL validation issue

### ISSUE THREAD

**Issue by kvuppala** [GSA/project-open-data-dashboard#51]
http://labs.data.gov/dashboard/validate
Using the  http://www.sba.gov/data.json  URL to validate, "Valid JSON" flag comes as false even when the json is correct, the same file when downloaded locally and validated through file upload shows as valid.

![sba_json_url_validation_issue](https://cloud.githubusercontent.com/assets/1738764/4560204/3d5ed322-4ef3-11e4-9f9b-520d6e375068.png)

**Comment by rebeccawilliams** [comment]
Has this been resolved?
