### ISSUE TITLE
ssl for https://labs.data.gov/dashboard

### ISSUE THREAD

**Issue by gbinal** [GSA/project-open-data-dashboard#67]
When on https://www.data.gov/labs/, if I then click on `Project Open Data Dashboard website`, I get a nasty ssl cert warning.  

![screen shot 2014-12-17 at 8 40 50 pm](https://cloud.githubusercontent.com/assets/633088/5482334/20dffdfe-862d-11e4-9e6d-5f930c213703.png)

**Comment by rebeccawilliams** [comment]
Looks like this was addressed.
