### ISSUE TITLE
Milestone 5 - incorrect data set totals

### ISSUE THREAD

**Issue by pdurusau** [GSA/project-open-data-dashboard#69]
Milestone 5 reports 372 datasets for the Department of Commerce, not the 23,181 listed at data.gov and the Department of Health and Human Resources has 1672 datasets, not the 1064 reported in Milestone 5.

The decline in datasets appears between Milestone 3 and Milestone 4, but is repeated in Milestone 5.

**Comment by rebeccawilliams** [comment]
@pdurusau This is based on data.json only, not geospatial data. I hope that clears things up.
