### ISSUE TITLE
icons not visible in IE 10

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/project-open-data-dashboard#70]
![unnamed 2](https://cloud.githubusercontent.com/assets/1725454/5635223/452e1190-95b5-11e4-999b-eea76e288beb.png)

**Comment by philipashlock** [comment]
I believe this is only an issue when security settings are specifically set to prevent fonts from loading which is not default behavior for IE.

**Comment by rebeccawilliams** [comment]
Closing this unless it comes up again.
