### ISSUE TITLE
Upgrade schema tool assigns all output records the same contactPoint

### ISSUE THREAD

**Issue by torrin47** [GSA/project-open-data-dashboard#72]
When using the schema conversion tool (http://labs.data.gov/dashboard/upgrade-schema) to batch upgrade from schema 1.0 to 1.1, all output records end up with the same contactPoint array containing the fn and hasEmail values of the last record in the uploaded file, rather than their respective values.

**Comment by philipashlock** [comment]
This was also impacting the `publisher` field. It should now be fixed with fa5bc4501bd5d245227a7d796243743165d5a6f6 which will go live on labs.data.gov tomorrow January 28th. Until then you can use the fixed tool on this staging server http://data-staging.civicagency.org/upgrade-schema

**Comment by philipashlock** [comment]
This is live on labs.data.gov/dashboard/upgrade-schema
