### ISSUE TITLE
Update CSV converter to support v1.1

### ISSUE THREAD

**Issue by philipashlock** [GSA/project-open-data-dashboard#81]
There's a current example of how you might represent some of the more complex v1.1 structure with a CSV on https://project-open-data.cio.gov/v1.1/metadata-resources/#sample-data-files

**Comment by philipashlock** [comment]
A beta version of this is now available at http://data-staging.civicagency.org/datagov/csv_to_json

**Comment by rebeccawilliams** [comment]
I believe this is complete, so I am closing this.
