### ISSUE TITLE
Non-federal v1.1 schema selection reverts to federal v1.1

### ISSUE THREAD

**Issue by philipashlock** [GSA/project-open-data-dashboard#85]
The v1.1 auto-detection is overriding the non-federal v1.1 selection. 

Currently selecting non-federal v1.0 should properly validate as non-federal v1.1 if the JSON has a v1.1 header/structure. 

cc @chrismetcalf

**Comment by philipashlock** [comment]
@chrismetcalf sorry about that. It looks like I broke this about a month ago with 83a02b6b73ea0e39443aa233646a9048a9f92953

This should be fixed now on http://data-staging.civicagency.org/validate and for the most part it will actually work on http://labs.data.gov/dashboard/validate if you specify Non-Federal v1.0 on a v1.1 file, but that doesn't yet include a recent refinement to the regex that impacts a lot of your datasets. See:
6c66b620a4d1110a36622fd09c10f33ed99bf5c9
fc01bc61360f73454011b5b1416f7b515cf2f4a9

All these updates should be live on labs.data.gov by Friday.

**Comment by chrismetcalf** [comment]
Awesome, thanks @philipashlock
