### ISSUE TITLE
Dashboard changes for May 31 milestone:

### ISSUE THREAD

**Issue by jlberryhill** [GSA/project-open-data-dashboard#96]
Team - what do you think about the following Dashboard changes for the 5/31 milestone?

Add agency data link quality error reports.

Governmentwide summary stats (/dashboard/ level) for:
- Data.gov views
- public/non-public/restricted composition
- % dataset growth from last quarter
- % of agencies with DAP on /data/ page
- % of bureaus represented
- % of programs represented
-  % of public datasets downloadable (i.e., "published")
- dataset link quality
- % of datasets with file formats that match format listed in data.json
- % datasets that are PDFs

EDI Tab:
- Rename "Is the EDI available on Data.gov?" Field to reflect when there are no redactions/everything is available via the PDL. 
- Think we should add something for # of datasets with redactions, and % of redacted datasets with explanations in "rights" metadata field?

PDL tab (I think these changes would also need to be made to EDI tab for agencies with redactions):
- Would need to add composition breakdown (public/restricted/non-public) like EDI tab currently has.
-To control for potential inadvertent incentives for agencies to not continue to catalog non-public datasets because they now need to be entered in the PDL, we should track increases/decreased in number of non-public datasets over time.
- Now that we have baseline on "views on data.gov for the quarter," let's add another box for increases/decreases. 
- Need % of public datasets with license information, as required by May 31 IDC guidance. 

I think that's everything floating around my head for now, but happy to hear other suggestions. @rebeccawilliams and @philipashlock, I'll set up a time to discuss for next week.

**Comment by philipashlock** [comment]
In talking with Jamie we decided:

* We'll keep the EDI tab separate from PDL regardless of how EDI is submitted, but we can rename the last EDI field from "Is the EDI available on Data.gov?" to "PDL includes non-public datasets and no redactions" 
* The non-public dataset change metrics would display under EDI
* We'll keep the accessLevel fields just under the EDI tab

**Comment by rebeccawilliams** [comment]
Broke these up into separate issues. Closing this.
